from .WEBPAGE_RESOLVE.webpage_resolver import WebpageResolver
from .ALEXA_RANK.alexa_rank import AlexaRank
from .IOSCO.iosco import IOSCOParse
from .SCAMWATCHER.scamwatcher import Scamwatcher
from .LANGUAGE_DETECTION.language_detection import LanguageDetection
from .poland_check.poland_check import PolandCheck
from .RGX_GAME.random_page_rgx import RandomRGXExtractor
from .tax_heaven.tax_heaven import TaxHeaven
from .WHO_IS.whois_api import WhoIs
from .KNF.knf import KNFCheck
